from pathlib import Path

from backend.config import settings
from backend.models.agent import AgentResponse
from backend.services.codegen import _slugify


def get_explainer_path(agent: AgentResponse) -> Path:
    return settings.agents_path / f"{_slugify(agent.name)}_explainer.md"


def generate_explainer(agent: AgentResponse) -> str:
    settings.agents_path.mkdir(parents=True, exist_ok=True)

    tools_section = ""
    if agent.tools:
        tools_list = "\n".join(f"- {t}" for t in agent.tools)
        tools_section = f"\n## Tools\n\nThis agent has access to:\n{tools_list}\n"

    schedule_section = ""
    if agent.schedule:
        schedule_section = f"\n## Schedule\n\nCron: `{agent.schedule}`\n"

    env_vars = "- `OPENROUTER_API_KEY` — required for OpenRouter models" if agent.provider == "openrouter" else "- No environment variables required (uses local Ollama)"

    content = f"""# {agent.name}

> Auto-generated by Agent Forge

## Overview

- **Model**: `{agent.model}` via {agent.provider}
- **Agent ID**: `{agent.id}`

## System Prompt

```
{agent.system_prompt or '(none)'}
```

## User Prompt Template

```
{agent.user_prompt_template or '(none)'}
```
{tools_section}{schedule_section}
## Running Standalone

```bash
{f'OPENROUTER_API_KEY=your_key python {_slugify(agent.name)}.py' if agent.provider == 'openrouter' else f'python {_slugify(agent.name)}.py'}
```

## Environment Variables

{env_vars}
"""

    path = get_explainer_path(agent)
    path.write_text(content)
    return str(path)


def remove_explainer(agent: AgentResponse) -> None:
    path = get_explainer_path(agent)
    if path.exists():
        path.unlink()
